#!/bin/bash
echo "choose"
select opt in video_information photo_information
do 
   if [ "$opt" == "video_information" ]
   then
       read -p "put your video :  " name
       mediainfo --fullscan "$name"
   fi
   if [ "$opt" == "photo_information" ]
   then
       read -p "put your photo : " photo
       exiftool "$photo"
   fi 
done 
